name: kkiapay_flutter_sdk
description: KkiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.0.5
support: kkiapay <support@kkiapay.me>
homepage: 'https://github.com/kkiapay/kkiapay-flutter-sdk'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

  #webview_flutter: ^0.3.1
  flutter_webview_plugin:
    git: https://github.com/nuc134r/flutter_webview_plugin.git
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
